In [34]:
import numpy as np

array_1 = np.arange(0, 10)
print(
    array_1
    , array_1 + 5
    , array_1 + array_1    # 2-массива должны-иметь размерОдинаковый
    , array_1 / array_1    # nan = not-a-number
    , array_1 / 0          # inf = infinity = бесконечность
    ,sep='\n'
)

[0 1 2 3 4 5 6 7 8 9]
[ 5  6  7  8  9 10 11 12 13 14]
[ 0  2  4  6  8 10 12 14 16 18]
[nan  1.  1.  1.  1.  1.  1.  1.  1.  1.]
[nan inf inf inf inf inf inf inf inf inf]


/var/folders/w6/p8ygz9l94mv7vcgrts0tz9b00000gn/T/ipykernel_5258/1782831427.py:8: RuntimeWarning: invalid value encountered in divide
  , array_1 / array_1    # nan = not-a-number
/var/folders/w6/p8ygz9l94mv7vcgrts0tz9b00000gn/T/ipykernel_5258/1782831427.py:9: RuntimeWarning: divide by zero encountered in divide
  , array_1 / 0          # inf = infinity = бесконечность
/var/folders/w6/p8ygz9l94mv7vcgrts0tz9b00000gn/T/ipykernel_5258/1782831427.py:9: RuntimeWarning: invalid value encountered in divide
  , array_1 / 0          # inf = infinity = бесконечность


In [40]:
# функцииУниверсальные
array_2 = np.arange(1, 11)
print(
    np.sqrt(array_2)
    ,np.sqrt(array_2)
    ,np.sin(array_2)
    ,np.log(array_2)
    ,array_2
    ,sep='\n'
)

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]
[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849 -0.54402111]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458 2.30258509]
[ 1  2  3  4  5  6  7  8  9 10]


In [54]:
print(
    array_2
    ,array_2.sum()
    ,array_2.mean()    # значение:среднее
    ,array_2.max()
    ,array_2.min()
    ,array_2.var()    # дисперсия
    ,array_2.std()    # отклонение:средне-квадратичное
    ,sep='\n'
)

[ 1  2  3  4  5  6  7  8  9 10]
55
5.5
10
1
8.25
2.8722813232690143


In [60]:
# вычислять:по-осям,измерениям
print(
    np.arange(0, 25)
    ,np.arange(0, 25).reshape(5,5)
    ,sep='\n\n'
)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [74]:
array_2d = np.arange(0, 25).reshape(5,5)

print(
    array_2d.sum()        # sum всех-строк и всех-колонок
    ,array_2d.sum(axis=1) # sum только-всех-строк
    ,array_2d.sum(axis=0) # sum только-всех-колонок
    ,sep='\n'
)

300
[ 10  35  60  85 110]
[50 55 60 65 70]
