In [9]:
# вариант-1. с-numpy
import numpy as np
from IPython.display import clear_output

df = np.zeros(9, dtype=int)
print(df.reshape(3, 3))

def check__winner(df):
    for a, b, c in [
        [0, 1, 2], [3, 4, 5], [6, 7, 8], # строки
        [0, 3, 6], [1, 4, 7], [2, 5, 8], # столбцы
        [0, 4, 8], [2, 4, 6]             # диагонали
    ]:
        if df[a] == df[b] == df[c] != 0:
            return df[a]  # Возвращаем номер игрока (1 или 2)

while 0 in df:
    df[int(input('player-1: ')) - 1] += 1
    clear_output()
    print(df.reshape(3, 3))
    
    winner = check__winner(df)
    if check__winner(df):
        print(f'победа игрока-{winner}')
        break
    if not 0 in df:
        print('ничья')
        break
        
    df[int(input('player-2: ')) - 1] += 2
    clear_output()
    print(df.reshape(3, 3))

    winner = check__winner(df)
    if check__winner(df):
        print(f'победа игрока-{winner}')
        break

[[2 2 2]
 [1 1 0]
 [1 0 0]]
победа игрока-2


In [ ]:
# вариант-2. без-numpy
from IPython.display import clear_output

df = [0] * 9
for i in range(3):
    print(df[i*3:(i+1)*3])

def check_winner(board):
    for a, b, c in [
        [0, 1, 2], [3, 4, 5], [6, 7, 8],  # строки
        [0, 3, 6], [1, 4, 7], [2, 5, 8],  # столбцы
        [0, 4, 8], [2, 4, 6]              # диагонали
    ]:
        if board[a] == board[b] == board[c] != 0:
            return board[a]  # Возвращаем номер игрока (1 или 2)

while 0 in df:
    # Ход первого игрока
    move = int(input('Player 1: ')) - 1
    if df[move] == 0:
        df[move] = 1
    else:
        print("Invalid move, try again.")
        continue
    clear_output()
    for i in range(3):
        print(df[i*3:(i+1)*3])
    
    winner = check_winner(df)
    if winner:
        print(f'Player {winner} wins!')
        break
    if not 0 in df:
        print('It\'s a draw!')
        break

    # Ход второго игрока
    move = int(input('Player 2: ')) - 1
    if df[move] == 0:
        df[move] = 2
    else:
        print("Invalid move, try again.")
        continue
    clear_output()
    for i in range(3):
        print(df[i*3:(i+1)*3])

    winner = check_winner(df)
    if winner:
        print(f'Player {winner} победил !')
        break

[1, 2, 1]
[0, 0, 0]
[0, 0, 0]


Player 2:  4


In [5]:
# вариант-3. c-numpy + с-проверкой, что ячейкаПустая
import numpy as np
from IPython.display import clear_output

df = np.zeros(9, dtype=int)
print(df.reshape(3, 3))

def check__winner(df):
    for a, b, c in [
        [0, 1, 2], [3, 4, 5], [6, 7, 8], # строки
        [0, 3, 6], [1, 4, 7], [2, 5, 8], # столбцы
        [0, 4, 8], [2, 4, 6]             # диагонали
    ]:
        if df[a] == df[b] == df[c] != 0:
            return df[a]  # Возвращаем номер игрока (1 или 2)

while 0 in df:
    move = int(input('player-1: ')) - 1
    if df[move] == 0:
        df[move] = 1
    else:
        print("Invalid move, try again.")
        continue
    clear_output()
    print(df.reshape(3, 3))
    
    winner = check__winner(df)
    if winner:
        print(f'победа игрока-{winner}')
        break
    if not 0 in df:
        print('ничья')
        break
        
    move = int(input('player-2: ')) - 1
    if df[move] == 0:
        df[move] = 2
    else:
        print("Invalid move, try again.")
        continue
    clear_output()
    print(df.reshape(3, 3))

    winner = check__winner(df)
    if winner:
        print(f'победа игрока-{winner}')
        break

[[1 2 2]
 [1 0 0]
 [1 0 0]]
победа игрока-1


In [7]:
# вариант-4. вроде-Идеальный
import numpy as np
from IPython.display import clear_output

df = np.zeros(9, dtype=int)
print(df.reshape(3, 3))

def check__winner(df):
    for a, b, c in [
        [0, 1, 2], [3, 4, 5], [6, 7, 8], # строки
        [0, 3, 6], [1, 4, 7], [2, 5, 8], # столбцы
        [0, 4, 8], [2, 4, 6]             # диагонали
    ]:
        if df[a] == df[b] == df[c] != 0:
            return df[a]  # Возвращаем номер игрока (1 или 2)

while 0 in df:
    for player in [1, 2]:
        move = int(input(f'player-{player}: ')) - 1
        if df[move] == 0:
            df[move] = player
            clear_output()
            print(df.reshape(3, 3))
        else:
            print("Invalid move, try again.")
    if (winner := check__winner(df)):
        print(f'победа игрока-{winner}')
        break

[[1 1 1]
 [2 2 2]
 [0 0 0]]
победа игрока-1
